version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  node:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev -- --host
    ports:
      - "5173:5173" 

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.enable_ipv4: "true"
